### ISSUE TITLE
Do i need to manage connection state by my self?

### ISSUE THREAD

**Issue by NailAgliev** [soft2tec/universal_mqtt_client#20]
Is the client status stream just for indication? Future of `client.connect()` resolves before the status stream gets `connected` status.

**Comment by lucacasonato** [comment]
> Is the client status stream just for indication?

Yes.

> Future of `client.connect()`resolves before the status stream gets `connected` status.

The future returned by `client.connect()` will resolve when client connects to the broker for the first time. It will reject if the inital connection to the broker is unsuccessful. If the `autoReconnect` option is enabled, the client will automatically try to reconnect. You can get the status of the client connection can through the `client.status` stream.

**Comment by lucacasonato** [comment]
Closing because stale.
